Adds a technical report
dedis/dela pull request #188
Opened 2021-05-12 12:54 UTC by nkcr

[Report.pdf](https://github.com/dedis/dela/files/6466245/Report.pdf)

2021-05-18 09:19 UTC, pierluca commented on core/execution/benchmark/Report.md
> +|Simple crypto |0.005 |          |      |0.237   |            |
Effectively, we can consider that the "increment" implementation is as good as testing the networking overhead. I don't see a need to measure them separately for now.

2021-05-19 09:59 UTC, gnarula requested changes
Looks good! Just need to update the curve operation we do in the contract.

2021-05-19 09:59 UTC, gnarula commented on core/execution/benchmark/Report.md
> +   points (A,B) and a scalar (S) in argument. It then performs (A+B)*S.
```suggestion
   simple operation on ed25519 elliptic curves. The smart contract takes a scalar (s) in argument. It then performs `s*G`, where `G` is the ed25519 base point.
```

2021-05-19 11:20 UTC, gnarula approved these changes
LGTM

2021-05-19 11:22 UTC, merged