Evoting
dedis/dela pull request #189
Opened 2021-05-12 15:01 UTC by A-Ibm

2021-05-13 12:47 UTC, A-Ibm commented
### **Remaining issue** 

The verification of the proof in the Neff Shuffle protocol fails sometimes, follow these instructions to reproduce the bug : 

1. run `go install` in _cli/node/memcoin_ and _cli/crypto_
2. cd to the root of the repo
3. run 3 nodes : `LLVL=info memcoin --config /tmp/node1 start --port 2001` , `LLVL=info memcoin --config /tmp/node2 start --port 2002` ,  `LLVL=info memcoin --config /tmp/node3 start --port 2003`
4. run the script `3nodes.sh`
5. run the following command : `memcoin --config /tmp/node1 e-voting scenarioTest --member $(memcoin --config /tmp/node1 dkg export) --member $(memcoin --config /tmp/node2 dkg export) --member $(memcoin --config /tmp/node3 dkg export)`

If you are lucky enough, you should see some` PROOF FAILED !!!!!!!!` printed in the CLI of nodes, if not, simply run the command at step 5 until a proof verification fails.

6. delete temp folders of _node1_ _node2_ and _node3_

2021-05-14 09:06 UTC, A-Ibm commented
### **Remaining Issue** 

I mentioned during our previous meeting we still have a nonce issue. We set the nonce of the newly pushed transaction by incrementing the nonce of the last transaction, however, at some point, the nonce is always incorrect and we end up not being able to push transactions anymore.

I thought we might have a concurrency issue when fetching the last block, but you were right, [fetching the last block](https://github.com/dedis/dela/blob/d-voting-code-refactoring/core/ordering/cosipbft/blockstore/disk.go#L242) is indeed thread safe. 

After some investigation, the last block happens to be filled with only rejected transactions. Hence, I fetch all the blocks until I find one filled with accepted transaction and I set nonce = max nonce + 1. You can find the code [here](https://github.com/dedis/dela/blob/d-voting-code-refactoring/contracts/evoting/controller/action.go#L1299). 

Everything seems to be working fine (apart from the [proof verification](https://github.com/dedis/dela/pull/189#issuecomment-840532035))

2021-05-26 08:39 UTC, nkcr requested changes
That's a lot to review there. This is a first round and I haven't looked at the neff shuffle implementation at all. It will come with a followup review. 

Please update this branch with master, which now includes a new action that will provide you a lot of hints (that's sonarcloud).

I see you put some efforts in the tests, thank for that! Otherwise I let you go through my comments. I found the code in general clear and readable, but there is still room for a lot of refactoring, especially in `evoting/controller/action.go` 😀 .

2021-05-26 08:39 UTC, nkcr commented on dkg/pedersen/controller/action.go
> +	http.HandleFunc(getPublicKeyEndPoint, func(w http.ResponseWriter, r *http.Request) {
should use the `mino/proxy`

2021-05-26 08:39 UTC, nkcr commented on dkg/pedersen/controller/action.go
> +	K, C, _, err := actor.Encrypt([]byte(plaintext))
don't use uppercase: 
k, c, kBuff, cBuff

2021-05-26 08:39 UTC, nkcr commented on dkg/pedersen/controller/action.go
> +	plaintext := "hello"
should be passed in the http body

2021-05-26 08:39 UTC, nkcr commented on go.mod
> +	github.com/satori/go.uuid v1.2.0
As we're already using `"github.com/rs/xid"` for generating GUID in mino, I would stick with it and not add a new dependency.

2021-05-26 08:39 UTC, nkcr commented on private.key
> +K�8�CS�}�t�^��ՙ5K�!��J���
this file shouldn't be there

2021-05-26 15:58 UTC, nkcr requested changes
Here is the rest of the review.

2021-05-26 15:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dedis/dela?pullRequest=189) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/dedis/dela?pullRequest=189) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: nkcr<br/>:x: A-Ibm<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dedis/dela?pullRequest=189) it.</sub>

2021-06-08 12:33 UTC, ineiti commented on shuffle/neff/handler.go
> +				} else {
there is no golint? I think it catches those...

2021-07-16 11:28 UTC, nkcr commented
Implementation moved in https://github.com/dedis/d-voting.

2021-07-16 11:28 UTC, closed without merging