Calypso - write secrets
dedis/dela pull request #250
Opened 2023-04-03 07:58 UTC by pierluca

2023-04-03 13:26 UTC, jbsv requested changes
is it possible to implement and test listSecrets at this stage ?

2023-04-03 13:26 UTC, jbsv commented on contracts/calypso/calypso.go
> +		}
'case CmdListSecrets:' missing ?

2023-04-11 21:35 UTC, pierluca commented
@jbsv Sorry, I had most things in place and forgot to add tests for LIST_SECRETS. 🤦  
Thank you for pointing that issue out.

2023-06-14 12:12 UTC, jbsv commented on contracts/calypso/calypso_test.go
> +	require.Equal(t, fmt.Sprintf("name1=secret1,name2=secret2"), buf.String())
unnecessary use of fmt.Sprintf (S1039)

2023-06-28 06:08 UTC, jbsv commented on contracts/calypso/calypso.go
>  	// CmdDeleteSmc defines a command to deleteSmc a SMC
```suggestion
	// CmdDeleteSmc defines a command to delete a SMC
```

2023-07-24 18:33 UTC, pierluca commented
Closing this PR as the logic was moved to the HBT repository.
https://github.com/dedis/hbt/pull/53

2023-07-24 18:33 UTC, closed without merging