add bls PublicKey GetPoint
dedis/dela pull request #253
Opened 2023-05-21 13:29 UTC by lourkeur

Simply an accessor. This would help with the DKG for F3B-IBE.

2023-05-23 12:31 UTC, pierluca commented
This seems to break the PublicKey abstraction, which arguably is only useful to hide underlying the kyber.Point.
Can you clarify why you need this, the problem you're trying to solve, etc. ?

2023-05-24 08:48 UTC, jbsv requested changes
align test with ed25519

2023-05-24 08:48 UTC, jbsv commented on crypto/bls/bls_test.go
> +	pk := PublicKey{point: point}
```suggestion
	pk := NewPublicKeyFromPoint(point)
```

2023-05-24 08:48 UTC, jbsv commented on crypto/bls/bls_test.go
> +	pk := PublicKey{point: point}
Should be the same test as [for the ed25519 implementation](https://github.com/dedis/dela/blob/6cd3d62903806f7863ff29a75c12c6c6bfe06085/crypto/ed25519/ed25519_test.go#L38), in which case the GetPoint() is needed.

2023-05-24 12:02 UTC, pierluca commented
Thank you @lourkeur for the clarification.
That makes sense 👍 
This works for me, the failing test is unrelated to this PR.

2023-05-30 14:18 UTC, jbsv approved these changes

2023-06-14 10:42 UTC, merged